rt = sfroot;
ch = rt.find('-isa','Stateflow.EMChart','Path',[mdl '/Path_Planner']);

ch.Script = sprintf([ ...
'function [y_target,target_speed] = Path_Planner(x_ego,y_ego,x_pred,y_pred,risk,replan)\n' ...
'\n' ...
'y_target = 0.0;\n' ...
'target_speed = 10.0;\n' ...
'\n' ...
'roadLeft = -4.0;\n' ...
'roadRight = 4.0;\n' ...
'\n' ...
'if replan > 0\n' ...
'    if y_pred >= y_ego\n' ...
'        if (y_ego - 2.5) >= roadLeft\n' ...
'            y_target = -2.5;\n' ...
'        else\n' ...
'            y_target = 2.5;\n' ...
'        end\n' ...
'    else\n' ...
'        if (y_ego + 2.5) <= roadRight\n' ...
'            y_target = 2.5;\n' ...
'        else\n' ...
'            y_target = -2.5;\n' ...
'        end\n' ...
'    end\n' ...
'    target_speed = 8.0;\n' ...
'end\n' ...
'\n' ...
'if y_target > roadRight\n' ...
'    y_target = roadRight;\n' ...
'elseif y_target < roadLeft\n' ...
'    y_target = roadLeft;\n' ...
'end\n' ...
'end\n']);